# Generated by Django 5.2 on 2025-04-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Valor Recebido')),
                ('origin', models.CharField(max_length=100, verbose_name='Origem')),
                ('date', models.DateField(verbose_name='Data Recebimento')),
            ],
        ),
    ]
