# Generated by Django 4.2 on 2025-03-29 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exp_name', models.CharField(max_length=200)),
                ('value', models.FloatField(blank=True, null=True)),
                ('payday', models.DateField(blank=True, null=True)),
                ('status', models.ForeignKey(default='Pendente', on_delete=django.db.models.deletion.CASCADE, related_name='expense_status', to='expenses.status')),
            ],
        ),
    ]
