# Generated by Django 5.2 on 2025-04-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_extract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='exp_name',
            field=models.CharField(max_length=200, verbose_name='Despesa'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='payday',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Pagamento'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor'),
        ),
    ]
